// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsEkvWNeBkRCDf4s41vE15B1qzkxFTYZE',
    appId: '1:1568594369:web:18043943c5967d536d3740',
    messagingSenderId: '1568594369',
    projectId: 'golawyer-3615c',
    authDomain: 'golawyer-3615c.firebaseapp.com',
    storageBucket: 'golawyer-3615c.firebasestorage.app',
    measurementId: 'G-WJWQH9E3G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8uL-7DMCQ6kfL1dJ0Av9hfHkRPoxLD08',
    appId: '1:1568594369:android:7bc211f3096a622b6d3740',
    messagingSenderId: '1568594369',
    projectId: 'golawyer-3615c',
    storageBucket: 'golawyer-3615c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-L4Ls7OnOCtyYcJ4bN_zNg_4WSDoXBeI',
    appId: '1:1568594369:ios:93743c8267b07cb36d3740',
    messagingSenderId: '1568594369',
    projectId: 'golawyer-3615c',
    storageBucket: 'golawyer-3615c.firebasestorage.app',
    iosBundleId: 'com.example.goLawyerAi',
  );
}
